@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Runner
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-07-10 02:15
rem
rem  ENTRY_MODE:
rem    file   -> python app.py
rem    module -> python -m package.module
rem    runner -> python -m runner_module [args...]
rem ============================================================

set "PROJECT_NAME=PDF Studio"
set "VENV_DIR=.venv"
set "ENTRY_MODE=file"
set "APP_ENTRY=src\pdf_reader.py"
set "RUNNER_ARGS="

set "PY=%CD%\%VENV_DIR%\Scripts\python.exe"

if not exist "%PY%" (
    echo [ERROR] Local venv not found: "%PY%"
    echo.
    echo Fix with:
    echo   python -m venv "%VENV_DIR%"
    echo   "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo   "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
    echo.
    pause
    exit /b 1
)

if /I "%ENTRY_MODE%"=="file" if not exist "%APP_ENTRY%" (
    echo [ERROR] Entry file not found: "%APP_ENTRY%"
    echo Edit run.bat or run with the correct entry file.
    pause
    exit /b 1
)

title "%PROJECT_NAME% - RUN"
echo ============================================================
echo  Running : %PROJECT_NAME%
echo  Project : %CD%
echo  Python  : %PY%
echo  Mode    : %ENTRY_MODE%
echo  Entry   : %APP_ENTRY%
if /I "%ENTRY_MODE%"=="runner" echo  Args    : %RUNNER_ARGS%
echo ============================================================
echo.

set "EXITCODE=0"

if /I "%ENTRY_MODE%"=="module" (
    "%PY%" -m %APP_ENTRY% %*
) else if /I "%ENTRY_MODE%"=="runner" (
    if defined RUNNER_ARGS (
        "%PY%" -m %APP_ENTRY% !RUNNER_ARGS! %*
    ) else (
        "%PY%" -m %APP_ENTRY% %*
    )
) else (
    "%PY%" "%APP_ENTRY%" %*
)

set "EXITCODE=!ERRORLEVEL!"

echo.
echo ============================================================
echo  Process exited with code: !EXITCODE!
echo ============================================================
pause
exit /b !EXITCODE!
