@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-07-10 02:15
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=PDF Studio"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDctMTAgMDI6MTUNCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9UERGIFN0dWRpbyIN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkVOVFJZX01PREU9ZmlsZSINCnNldCAiQVBQX0VO
        echo VFJZPXNyY1xwZGZfcmVhZGVyLnB5Ig0Kc2V0ICJSVU5ORVJfQVJHUz0iDQoNCnNldCAiUFk9JUNE
        echo JVwlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4ZSINCg0KaWYgbm90IGV4aXN0ICIlUFklIiAo
        echo DQogICAgZWNobyBbRVJST1JdIExvY2FsIHZlbnYgbm90IGZvdW5kOiAiJVBZJSINCiAgICBlY2hv
        echo Lg0KICAgIGVjaG8gRml4IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9E
        echo SVIlIg0KICAgIGVjaG8gICAiJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiIC1tIHBpcCBp
        echo bnN0YWxsIC0tdXBncmFkZSBwaXANCiAgICBlY2hvICAgIiVWRU5WX0RJUiVcU2NyaXB0c1xweXRo
        echo b24uZXhlIiAtbSBwaXAgaW5zdGFsbCAtciByZXF1aXJlbWVudHMudHh0DQogICAgZWNoby4NCiAg
        echo ICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQppZiAvSSAiJUVOVFJZX01PREUlIj09ImZpbGUi
        echo IGlmIG5vdCBleGlzdCAiJUFQUF9FTlRSWSUiICgNCiAgICBlY2hvIFtFUlJPUl0gRW50cnkgZmls
        echo ZSBub3QgZm91bmQ6ICIlQVBQX0VOVFJZJSINCiAgICBlY2hvIEVkaXQgcnVuLmJhdCBvciBydW4g
        echo d2l0aCB0aGUgY29ycmVjdCBlbnRyeSBmaWxlLg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAxDQop
        echo DQoNCnRpdGxlICIlUFJPSkVDVF9OQU1FJSAtIFJVTiINCmVjaG8gPT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBSdW5uaW5n
        echo IDogJVBST0pFQ1RfTkFNRSUNCmVjaG8gIFByb2plY3QgOiAlQ0QlDQplY2hvICBQeXRob24gIDog
        echo JVBZJQ0KZWNobyAgTW9kZSAgICA6ICVFTlRSWV9NT0RFJQ0KZWNobyAgRW50cnkgICA6ICVBUFBf
        echo RU5UUlklDQppZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgZWNobyAgQXJncyAgICA6ICVS
        echo VU5ORVJfQVJHUyUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQplY2hvLg0KDQpzZXQgIkVYSVRDT0RFPTAiDQoNCmlmIC9J
        echo ICIlRU5UUllfTU9ERSUiPT0ibW9kdWxlIiAoDQogICAgIiVQWSUiIC1tICVBUFBfRU5UUlklICUq
        echo DQopIGVsc2UgaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJydW5uZXIiICgNCiAgICBpZiBkZWZpbmVk
        echo IFJVTk5FUl9BUkdTICgNCiAgICAgICAgIiVQWSUiIC1tICVBUFBfRU5UUlklICFSVU5ORVJfQVJH
        echo UyEgJSoNCiAgICApIGVsc2UgKA0KICAgICAgICAiJVBZJSIgLW0gJUFQUF9FTlRSWSUgJSoNCiAg
        echo ICApDQopIGVsc2UgKA0KICAgICIlUFklIiAiJUFQUF9FTlRSWSUiICUqDQopDQoNCnNldCAiRVhJ
        echo VENPREU9IUVSUk9STEVWRUwhIg0KDQplY2hvLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFByb2Nlc3MgZXhp
        echo dGVkIHdpdGggY29kZTogIUVYSVRDT0RFIQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnBhdXNlDQpleGl0IC9iICFFWElU
        echo Q09ERSENCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDctMTAgMDI6MTUNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA3LTEw
        echo IDAyOjE1DQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9UERGIFN0dWRpbyINCnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkFDVElWQVRFPSVD
        echo RCVcJVZFTlZfRElSJVxTY3JpcHRzXGFjdGl2YXRlLmJhdCINCg0KaWYgbm90IGV4aXN0ICIlQUNU
        echo SVZBVEUlIiAoDQogICAgZWNobyBbRVJST1JdIExvY2FsIHZlbnYgd2FzIG5vdCBmb3VuZDoNCiAg
        echo ICBlY2hvICAgICAgICAgIiVBQ1RJVkFURSUiDQogICAgZWNoby4NCiAgICBlY2hvIENyZWF0ZSBp
        echo dCB3aXRoOg0KICAgIGVjaG8gICAgICAgICBweXRob24gLW0gdmVudiAiJVZFTlZfRElSJSINCiAg
        echo ICBlY2hvLg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCnRpdGxlICIlUFJPSkVDVF9O
        echo QU1FJSAtIFZFTlYgU0hFTEwiDQpjYWxsICIlQUNUSVZBVEUlIg0KDQplY2hvID09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAg
        echo UHJvamVjdCBzaGVsbCBhY3RpdmF0ZWQNCmVjaG8gIFByb2plY3Q6ICIlQ0QlIg0KZWNobyAgUHl0
        echo aG9uIDoNCndoZXJlIHB5dGhvbg0KZWNobyAgVHlwZSAiZXhpdCIgdG8gbGVhdmUgdGhpcyBzaGVs
        echo bC4NCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09DQplY2hvLg0KY21kIC9rDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNy0xMCAwMjoxNQ0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1QREYgU3R1
        echo ZGlvIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiUFk9JUNEJVwlVkVOVl9ESVIlXFNjcmlw
        echo dHNccHl0aG9uLmV4ZSINCg0KaWYgbm90IGV4aXN0ICIlUFklIiAoDQogICAgZWNobyBbRVJST1Jd
        echo IExvY2FsIHZlbnYgbm90IGZvdW5kOiAiJVBZJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3JlYXRl
        echo IGl0IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0KICAgIHBh
        echo dXNlDQogICAgZXhpdCAvYiAxDQopDQoNCnRpdGxlICIlUFJPSkVDVF9OQU1FJSAtIFNZTkMiDQoN
        echo CmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09DQplY2hvICBTeW5jaW5nOiAlUFJPSkVDVF9OQU1FJQ0KZWNobyAgUHl0aG9uIDog
        echo JVBZJQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT0NCmVjaG8uDQoNCmVjaG8gWzEvM10gVXBncmFkaW5nIHBpcC4uLg0KZWNo
        echo byA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT0NCiIlUFklIiAtbSBwaXAgaW5zdGFsbCAtLXVwZ3JhZGUgcGlwDQplY2hvLg0KDQppZiBl
        echo eGlzdCAicmVxdWlyZW1lbnRzLnR4dCIgKA0KICAgIGVjaG8gWzIvM10gSW5zdGFsbGluZyBmcm9t
        echo IHJlcXVpcmVtZW50cy50eHQuLi4NCiAgICBlY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KICAgICIlUFklIiAtbSBwaXAgaW5z
        echo dGFsbCAtciByZXF1aXJlbWVudHMudHh0DQogICAgZWNoby4NCikgZWxzZSAoDQogICAgZWNobyBb
        echo Mi8zXSBTS0lQUEVEOiBObyByZXF1aXJlbWVudHMudHh0IGZvdW5kLg0KICAgIGVjaG8gICAgICAg
        echo Q3JlYXRlIG9uZSB3aXRoOiBwaXAuYmF0IGZyZWV6ZSBePiByZXF1aXJlbWVudHMudHh0DQogICAg
        echo ZWNoby4NCikNCg0KZWNobyBbMy8zXSBEZXBlbmRlbmN5IGhlYWx0aCBjaGVjay4uLg0KZWNobyA9
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT0NCiIlUFklIiAtbSBwaXAgY2hlY2sNCmVjaG8uDQoNCmVjaG8gPT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBTWU5DIENP
        echo TVBMRVRFDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgMA0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTEwIDAyOjE1DQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPVBERiBTdHVkaW8iDQpz
        echo ZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJFTlRSWV9NT0RFPWZpbGUiDQpzZXQgIkFQUF9FTlRS
        echo WT1zcmNccGRmX3JlYWRlci5weSINCnNldCAiUlVOTkVSX0FSR1M9Ig0Kc2V0ICJQWT0lQ0QlXCVW
        echo RU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQplY2hvID09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUFJPSkVDVCBE
        echo T0NUT1I6ICVQUk9KRUNUX05BTUUlDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUHJvamVjdCA6ICVDRCUNCmVj
        echo aG8gIE1vZGUgICAgOiAlRU5UUllfTU9ERSUNCmVjaG8gIEVudHJ5ICAgOiAlQVBQX0VOVFJZJQ0K
        echo aWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJydW5uZXIiIGVjaG8gIEFyZ3MgICAgOiAlUlVOTkVSX0FS
        echo R1MlDQplY2hvLg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hvIFtGQUlMXSB2ZW52
        echo IG5vdCBmb3VuZCBhdDogIiVQWSUiDQogICAgZWNoby4NCiAgICBlY2hvIENyZWF0ZSBpdCB3aXRo
        echo Og0KICAgIGVjaG8gICBweXRob24gLW0gdmVudiAiJVZFTlZfRElSJSINCiAgICBwYXVzZQ0KICAg
        echo IGV4aXQgL2IgMQ0KKQ0KDQplY2hvIFtPS10gdmVudiBmb3VuZDogIiVQWSUiDQplY2hvLg0KDQpl
        echo Y2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLQ0KZWNobyAgUHl0aG9uIEVudmlyb25tZW50DQplY2hvIC0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQWSUiIC1jICJp
        echo bXBvcnQgc3lzOyBwcmludCgnRXhlY3V0YWJsZSA6Jywgc3lzLmV4ZWN1dGFibGUpOyBwcmludCgn
        echo VmVyc2lvbiAgICA6Jywgc3lzLnZlcnNpb24uc3BsaXQoKVswXSk7IHByaW50KCdQcmVmaXggICAg
        echo IDonLCBzeXMucHJlZml4KSINCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBwaXAgdmVyc2lvbg0K
        echo ZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0NCiIlUFklIiAtbSBwaXAgLS12ZXJzaW9uDQplY2hvLg0KDQplY2hvIC0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNo
        echo byAgSW5zdGFsbGVkIFBhY2thZ2VzDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQWSUiIC1tIHBpcCBsaXN0DQplY2hv
        echo Lg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLQ0KZWNobyAgRGVwZW5kZW5jeSBIZWFsdGgNCmVjaG8gLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIg
        echo LW0gcGlwIGNoZWNrDQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgRW50cnkgUG9pbnQgQ2hlY2sN
        echo CmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tDQppZiAvSSAiJUVOVFJZX01PREUlIj09ImZpbGUiICgNCiAgICBpZiBleGlzdCAi
        echo JUFQUF9FTlRSWSUiICgNCiAgICAgICAgZWNobyBbT0tdIEVudHJ5IGZpbGUgZm91bmQ6ICIlQVBQ
        echo X0VOVFJZJSINCiAgICApIGVsc2UgKA0KICAgICAgICBlY2hvIFtGQUlMXSBFbnRyeSBmaWxlIE5P
        echo VCBmb3VuZDogIiVBUFBfRU5UUlklIg0KICAgICkNCikgZWxzZSAoDQogICAgIiVQWSUiIC1jICJp
        echo bXBvcnQgaW1wb3J0bGliLnV0aWwsIHN5czsgbmFtZT1yJyVBUFBfRU5UUlklJzsgc3BlYz1pbXBv
        echo cnRsaWIudXRpbC5maW5kX3NwZWMobmFtZSk7IHByaW50KCgnW09LXSBNb2R1bGUgZm91bmQ6ICcg
        echo aWYgc3BlYyBlbHNlICdbRkFJTF0gTW9kdWxlIE5PVCBmb3VuZDogJykgKyBuYW1lKTsgc3lzLmV4
        echo aXQoMCBpZiBzcGVjIGVsc2UgMSkiIDI+bnVsDQogICAgaWYgZXJyb3JsZXZlbCAxIGVjaG8gW0ZB
        echo SUxdIE1vZHVsZSBpbXBvcnQgdGVzdCBmYWlsZWQuDQogICAgaWYgL0kgIiVFTlRSWV9NT0RFJSI9
        echo PSJydW5uZXIiIGVjaG8gW0lORk9dIFJ1bm5lciBhcmdzOiAiJVJVTk5FUl9BUkdTJSINCikNCmVj
        echo aG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tDQplY2hvICBQcm9qZWN0IEZpbGVzDQplY2hvIC0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KaWYgZXhpc3Qg
        echo InV2LmxvY2siICAgICAgICAgIGVjaG8gW09LXSAgIHV2LmxvY2sgZm91bmQNCmlmIGV4aXN0ICJw
        echo eXByb2plY3QudG9tbCIgICBlY2hvIFtPS10gICBweXByb2plY3QudG9tbCBmb3VuZA0KaWYgZXhp
        echo c3QgInJlcXVpcmVtZW50cy50eHQiIGVjaG8gW09LXSAgIHJlcXVpcmVtZW50cy50eHQgZm91bmQN
        echo CmlmIG5vdCBleGlzdCAicmVxdWlyZW1lbnRzLnR4dCIgZWNobyBbV0FSTl0gcmVxdWlyZW1lbnRz
        echo LnR4dCBtaXNzaW5nDQplY2hvLg0KDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgRE9DVE9SIENPTVBMRVRFDQpl
        echo Y2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgMA0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
rem (test.bat not included)
echo ============================================================
pause
exit /b 0
